#!/usr/bin/env bash
set -euo pipefail

if ! command -v brew &>/dev/null; then
  echo "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! command -v stow &>/dev/null; then
  echo "Installing stow..."
  brew install stow
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
  # Needed for tmux plugins
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

stow -R nvim tmux git bin mise
