#!/usr/bin/env bash

if test ! $(which brew); then
  echo "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if test ! $(which stow); then
  echo "Installing stow..."
  brew install stow
fi

# Needed for tmux plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

stow -R nvim tmux git
