#!/usr/bin/env bash

if test ! $(which brew); then
  echo "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if test ! $(which stow); then
  echo "Installing stow..."
  brew install stow
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
  # Needed for tmux plugins
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

stow -R nvim tmux git bin
