require("user.packer")

require("user.autopairs")
require("user.comment")
require("user.lsp")
require("user.lualine")
require("user.settings")
require("user.telescope")
require("user.colorscheme")
require("user.keymap")
require("hop").setup()
